package quickfix.utils.professions

val ProfessionNames = listOf(
    "Abogacía",
    "Albañilería",
    "Arquitectura",
    "Carpintería",
    "Cerrajería",
    "Electricidad",
    "Fletes",
    "Fotografía",
    "Fumigación",
    "Gasfitería",
    "Jardinería",
    "Lavandería",
    "Limpieza",
    "Mascotas",
    "Mayores",
    "Mecánica",
    "Mudanzas",
    "Niños",
    "Otros",
    "Pinturería",
    "Plomería",
    "Reparaciones",
    "Seguridad",
    "Tapicería",
    "Techos",
    "Tecnología",
    "Textilería"
)