server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickfix?createDatabaseIfNotExist=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security: #https://www.browserling.com/tools/sha2-hash output=512
  secret-key: << >>
  access-token-minutes: 300
