server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /quickfix-api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickfix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: quickfix.app.noreply@gmail.com
    password: qgujxcoxggxmiyfr

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# Para activar el Trace
logging:
  level:
    root: INFO