server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickfix
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security:
  secret-key: '<<SECRET>>'
  access-token-minutes: 300
