server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /quickfix-api

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5433/quickFix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#logging:
#  level:
#    root: TRACE | DEBUG | INFO | WARN | ERROR | OFF