server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /quickfix-api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quickfix
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        #from here
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: trace

  mail:
    host: smtp.gmail.com
    port: 587
    username: quickfix.app.noreply@gmail.com
    password: qgujxcoxggxmiyfr

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

# Para activar el Trace
logging:
  level:
    root: INFO
    #from here
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate: info
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: info
    org.hibernate.cache: debug
    org.hibernate.orm.jdbc.extract: trace
    #to here

security:
  secret-key: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
  access-token-minutes: 300
